import QueryProvider from "@/app/QueryProvider";
import Footer from "@/components/footer/page";
import Header from "@/components/header/page";
import "./globals.css";

export const metadata = {
  title: "판다마켓",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body className="font-pretendard">
        <QueryProvider>
          <Header />
          <main>{children}</main>
          <Footer />
        </QueryProvider>
      </body>
    </html>
  );
}
