import Footer from "@/components/footer/page";
import "./globals.css";
import Header from "@/components/header/page";

export const metadata = {
  title: "판다마켓",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body className="font-pretendard">
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
